"""initial_schema

Revision ID: 60faa62647b9
Revises:
Create Date: 2026-08-27 14:07:57.279688

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '60faa62647b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
