"""add_users_webhooks_and_indexes

Revision ID: 826e99a35f89
Revises: 60faa62647b9
Create Date: 2026-08-27 18:10:53.201890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826e99a35f89'
down_revision: Union[str, Sequence[str], None] = '60faa62647b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_merchant_id'), 'users', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_merchant_id'), 'webhook_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_payload_hash'), 'webhook_events', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_webhook_events_received_at'), 'webhook_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.add_column('audit_events', sa.Column('merchant_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_audit_events_merchant_id'), 'audit_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_key_metadata_created_at'), 'key_metadata', ['created_at'], unique=False)
    op.create_index(op.f('ix_key_metadata_status'), 'key_metadata', ['status'], unique=False)
    op.create_index(op.f('ix_payment_tokens_created_at'), 'payment_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_tokens_merchant_id'), 'payment_tokens', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_tokens_status'), 'payment_tokens', ['status'], unique=False)
    op.add_column('risk_assessments', sa.Column('merchant_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_risk_assessments_calculated_at'), 'risk_assessments', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_card_id'), 'risk_assessments', ['card_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_composite_score'), 'risk_assessments', ['composite_score'], unique=False)
    op.create_index(op.f('ix_risk_assessments_merchant_id'), 'risk_assessments', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_token_id'), 'risk_assessments', ['token_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_transaction_id'), 'risk_assessments', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_security_cases_card_id'), 'security_cases', ['card_id'], unique=False)
    op.create_index(op.f('ix_security_cases_created_at'), 'security_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_cases_merchant_id'), 'security_cases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_security_cases_status'), 'security_cases', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_token_id'), 'transactions', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_token_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_security_cases_status'), table_name='security_cases')
    op.drop_index(op.f('ix_security_cases_merchant_id'), table_name='security_cases')
    op.drop_index(op.f('ix_security_cases_created_at'), table_name='security_cases')
    op.drop_index(op.f('ix_security_cases_card_id'), table_name='security_cases')
    op.drop_index(op.f('ix_risk_assessments_transaction_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_token_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_merchant_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_composite_score'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_card_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_calculated_at'), table_name='risk_assessments')
    op.drop_column('risk_assessments', 'merchant_id')
    op.drop_index(op.f('ix_payment_tokens_status'), table_name='payment_tokens')
    op.drop_index(op.f('ix_payment_tokens_merchant_id'), table_name='payment_tokens')
    op.drop_index(op.f('ix_payment_tokens_created_at'), table_name='payment_tokens')
    op.drop_index(op.f('ix_key_metadata_status'), table_name='key_metadata')
    op.drop_index(op.f('ix_key_metadata_created_at'), table_name='key_metadata')
    op.drop_index(op.f('ix_audit_events_merchant_id'), table_name='audit_events')
    op.drop_column('audit_events', 'merchant_id')
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_received_at'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_payload_hash'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_merchant_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_merchant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
